#pragma once
#include <windows.h>
#include <vector>
#include <assert.h>
#include <algorithm>
#include <numeric>
#include <intsafe.h>
#include <atlbase.h>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <fstream>
#include <sstream>
#include <string>
#include <wincrypt.h>
#include <memory>
#include <functional>

#include "MungeTLS.h"
#include "MungeCrypto.h"
#include "MungeWinHelpers.h"
#include "mtls_helper.h"
